# Generated by Django 4.2.5 on 2023-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('desk', models.TextField(max_length=1000)),
            ],
        ),
    ]
