# Generated by Django 4.2.5 on 2023-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproduct',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
