# Generated by Django 4.2.5 on 2023-11-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_listproduct_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listproduct',
            old_name='desk',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='listproduct',
            old_name='img',
            new_name='image',
        ),
    ]
