# Generated by Django 4.2.5 on 2023-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_rename_qty_listproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='listproduct',
            name='seller',
            field=models.CharField(max_length=255),
        ),
    ]
