# Generated by Django 4.2.5 on 2023-12-12 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_address', models.CharField(max_length=255)),
                ('delevery_service', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('current_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datasellers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
